### ISSUE TITLE
Date query on Oracle-based AGS services crashes

### ISSUE THREAD

**Issue by alsFC** [conterra/mapapps-query-builder#1]
When specifying a query using a date-field (type 'Date' in Oracle) on an Oracle-based AGS map service (AGS 10.3.1) the map server query crashes with the following error in AGS log:

Geodatabase error: Underlying DBMS error [ORA-01861: Literal stimmt nicht mit Formatzeichenfolge überein]

**Comment by matthiasstein** [comment]
Can you provide me the service url to investigate this issue?

**Comment by alsFC** [comment]
http://vsdev1521.esri-de.com:6080/arcgis/rest/services/GeoWorld_WM/net_events/MapServer/1

Field: BEGIN_DATETIME

**Comment by matthiasstein** [comment]
At this time the Complex Query does not support native date queries. The query must be "where=zeitpunkt <= timestamp '2015-10-05'" but the query builder uses "where=zeitpunkt <= '2015-10-05'". It seems that not every underlying database supports this.

**Comment by alsFC** [comment]
OK, I think it would be a good idea to list the fully supported DBMS.. or to list known issues of query-builder with DBMS supported by ArcGIS for Server. Unfortunately Oracle is one of the most important I guess.. 
At least the error handling with map.apps could be improved because no message appears in the web application when AGS answers on failed queries.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/v3.1.7 and map.apps 3.4.0.
