### ISSUE TITLE
contentviewer rules are not applied for features queried by query builder

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-query-builder#10]
## Reproduction
- Create an app that uses a custom template in the contentviewer
- The contentviewer definition is defined for both MapModelNodeID and AGSStore, thus: `"contentRules": [
               {
                  "matches": {
                     "context": {
                        "$or": [
                           {
                              "storeId": "_AGS_STORE_1488378066332"
                           },
                           {
                              "mapModelNodeId": "service_48664_1488378033813/0"
                           }
                        ]
                     }
                  },`
- Execute a query builder-query 
- Klick on a resultcenter entry (1) or on the feature on the map (2)

## Expected
- The customtemplate of the contentviewer is applied

## Actual
- (1) The standard contentviewer GRID layout is applied
- (2) The overlay does not allow a featureinfo on the feature
- Thus, the contentviewer rules are not applied for features that were queried by the query builder

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/3.2.3.

Use the "querybuilder_" prefix to match your content rule.
Sample:
```
"matches": {
  "context": {
    "$or": [
      {
        "storeId": "_AGS_STORE_1453414124872"
      },
      {
        "storeId": "querybuilder__AGS_STORE_1453414124872"
      }
    ]
  }
}
```
