### ISSUE TITLE
Entries in Live Configuration are missing

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-query-builder#11]
## Reproduction
- Use querybuilder 3.2.2 with map.apps 3.7.0
- Open Live Configuration

## Expected
- Entries "Grundeinstellungen", "UserQueryBuilderWidget", "QueryTools" appear

## Actual
- Only "Grundeinstellungen" appears

**Comment by matthiasstein** [comment]
This issue can not be replicated.

**Comment by oliverkosky** [comment]
Unfortunately, I have to reopen that issue as I can reproduce it again, this time both English and German version.

"Grundeinstellungen" is the only entry appearing in Live Configuration.
