### ISSUE TITLE
Feature Wish: allow queries on tables (without geometry)

### ISSUE THREAD

**Issue by schenardi** [conterra/mapapps-query-builder#13]
Allow queries based on tables. 
Currently, the QueryController.js gives an error when trying to transform non existing geometries in the function:

> ct_when(this._coordinateTransformer.transform(geometries, wkid), function (transformedGeometries) { ...}

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/3.2.4
