### ISSUE TITLE
GEONIS forms cannot be opened from resultcenter

### ISSUE THREAD

**Issue by schenardi** [conterra/mapapps-query-builder#15]
GEONIS forms do not open from resultcenter.

Suggested fix from our developert (tested with an earlier version 3.2.6 in a project):

QueryController.js, Line 105:

var memorySelectionStore = new MemorySelectionStore({
                        id: store.id || "querybuilderMemorySelectionStore",

**Comment by matthiasstein** [comment]
This line has already been changed to:
`id: "querybuilder_" + store.id,`

Have you encountered any problems using the same store id?

**Comment by schenardi** [comment]
We had these problem in a project and solved it as mentioned above. 
Right now I'm having another customer which installed the latest version and it's not working.

**Comment by ewpGISSupport** [comment]
I am the customer mentioned by schenardi. I am using dn_querybuilder 3.2.5 with map.apps 3.9. If I use dn_querybuilder for selection, GEONIS reports cannot be opened from resultcenter. If I use the normal selection tool, GEONIS reports can be opened from resultcenter. If it helps, I can provide you with an example app. We need these reports to work, we have customers waiting for them.

**Comment by schenardi** [comment]
the id of the store must match the store-id with the GEONIS form definition.
If I set 
id: "querybuilder_" + store.id,

then it works with GEONIS attribute forms.

**Comment by matthiasstein** [comment]
Thanks for the information. The prefix is required, as a so-called MemorySelectionStore is filled with the results for each query. This allows the user to delete individual results from the Result Center and should not have the same ID as the original store. I have added the property _useMemorySelectionStore_ , which allows you to influence the use of the MemorySelectionStore. If set to false, the original store will be used and set to DataModel. However, this means that the results can no longer be deleted in the Result Center.

```
"QueryBuilderProperties": {
        "enableDistinctValues": true,
        "defaultRelationalOperator": "$or",
        "searchEverywhereAsDefault": true,
        "useMemorySelectionStore": false
}
```
