### ISSUE TITLE
Is posible to perform a subquery using the QueryBuilder-Bundle 3.X?

### ISSUE THREAD

**Issue by katahV** [conterra/mapapps-query-builder#21]
We would like to use the query builder to perform a query against a FeatureService using the values retrieved from an auxiliary Table, where some values are stored. The auxiliary Table has a n:m relatioship with the Feature Service.
it would be something like that in SQL:
`SELECT * FROM locationsFLC 
 where LOCATION_ID (
     SELECT LOCATION_ID FROM auxTable 
     where DIVISION = X)`

Question:
Is there a possibility to make it only through configuration? 
If yes: Do you have any samples?
Thanks in advance!

**Comment by matthiasstein** [comment]
Your described requirement is not supported by the QueryBuilder. This behavior cannot be achieved by configuration. I will add your requirement to our list of improvements.

**Comment by katahV** [comment]
it won't be implemented?

**Comment by matthiasstein** [comment]
We have closed this issue as we will not continue to develop the QueryBuilder for line 3.
