### ISSUE TITLE
UserQueryBuilderWidgetFactory throws unexpected error

### ISSUE THREAD

**Issue by JoergArnold** [conterra/mapapps-query-builder#26]
Hi,

in map.apps V 4.7.2 we using Line 3 Apps together with SDi-Extension V 4.0.3.
When we use the sdi_srschanger-tool the map-context from the app will be "reinitialized" as designed, but in this case the console logs the following error:

Component._releaseComponentContext: Component 'UserQueryBuilderWidgetFactory' of bundle 'Bundle[29]-dn_querybuilder-v3.4.5:ACTIVE' method 'deactivate' in class 'UserQueryBuilderWidgetFactory' throws unexpected error! {canceled: false, type: "UNKNOWN", cause: TypeError: this.disconnect is not a function
    at Object.deactivate (https://edn-geoservices.stad…, message: "this.disconnect is not a function", msg: "this.disconnect is not a function", …}canceled: falsecause: TypeError: this.disconnect is not a function
    at Object.deactivate
(...more lines follow...)

Is it a fault of the dn_querybuilder-bundle or is it a fault of the sdi_srschanger-bundle..?
Can you help in this case please?

Best regards,
Jörg Arnold

**Comment by matthiasstein** [comment]
This bug was fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/3.4.6. Could you try and see if the error persists?

**Comment by JoergArnold** [comment]
Now it works fine. Thank You.
