### ISSUE TITLE
Mandatory dependency of authentication-bundle should be removed from dn_queryplaceholder-bundle

### ISSUE THREAD

**Issue by alsFC** [conterra/mapapps-query-builder#3]
When skipping "authentication" in skipBundles Queybuilder doesn't come up because dn_queryplaceholder-bundle can't be started because of missing dependency of authentication-bundle.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/v3.1.5
