### ISSUE TITLE
Bundles does not work together: "dn_printingenhanced" and "dn_querybuilder" in the same Line 4 App

### ISSUE THREAD

**Issue by JoergArnold** [conterra/mapapps-query-builder#31]
If I put both bundles (latest versions) in the same app, i got the follwing console error for dn_printingenhanced-bundle:

`TypeError: "ComponentReferenceController._injectService: Exception during injection of reference 'mapWidgetModel' with service:'undefined'
    cause of TypeError: this[c] is undefined"
    Dojo 29
layer.js:1221:285
    Dojo 27
Component.activate: Component 'PrintingPreviewController' of bundle 'Bundle[25]-dn_printingenhanced-v1.1.5:ACTIVE' error during activation of component 'PrintingPreviewController'!  ACTIVATION_ERROR: "Component._createComponentContext: Component 'PrintingPreviewController' of bundle 'Bundle[25]-dn_printingenhanced-v1.1.5:ACTIVE' component context can't be created, impl: 'PrintingPreviewController'!
    cause of TypeError: ComponentReferenceController._injectService: Exception during injection of reference 'mapWidgetModel' with service:'undefined'
    cause of TypeError: this[c] is undefined"
    Dojo 29
layer.js:1173:375
    Dojo 10`

Every bundle on its own in an app works.
I ask for support.

With kind regards
Jörg Arnold

**Comment by matthiasstein** [comment]
I cannot reproduce this error. In this app both bundles run together without any problems: https://demos.conterra.de/sandbox/resources/apps/printingenhancedquerybuildertest

Do you use any other bundles?

**Comment by JoergArnold** [comment]
We use a lot of other bundles .. but I can trace it back to this combination in my app
When I open the demo link from you, the same happens on my PC as you can see in the screenshot below.

![Demo_App](https://user-images.githubusercontent.com/33632121/89616111-13596900-d888-11ea-947a-8cc7428a323c.JPG)
.

**Comment by matthiasstein** [comment]
Which Firefox version do you use? Can you try to use another browser?

**Comment by matthiasstein** [comment]
It looks like there's a timing problem. I can rarely recreate the error. I have added new bundle test versions to the app. Could you test it again?
https://demos.conterra.de/sandbox/resources/apps/printingenhancedquerybuildertest

**Comment by JoergArnold** [comment]
It does indeed seem to be due to the version of the browser:

Problem exists with FireFox: 68.10.0esr (64-Bit)      (our standard-browser at work) 

Google Chrome: Version 84.0.4147.105 (Offizieller Build) (64-Bit) workes fine.

**Comment by JoergArnold** [comment]
> It looks like there's a timing problem. I can rarely recreate the error. I have added new bundle test versions to the app. Could you test it again?
> https://demos.conterra.de/sandbox/resources/apps/printingenhancedquerybuildertest
> 

Now the demo works in FireFox.

**Comment by matthiasstein** [comment]
Great I will release new versions of the bundles.

**Comment by JoergArnold** [comment]
After installing the new releases it works fine.. 
Thank you
