### ISSUE TITLE
Sample app not working in map.apps 4.12-SNAPSHOT

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-query-builder#36]
The provided sample application does not work with map.apps 4.12. 

No queryable data is available. 
Metadata for the Stores cannot be loaded as they do not contain queryable fields.
None of the predefined queries can be executed as the related stores are undefined.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/4.10.3
