### ISSUE TITLE
Disable distinct value query for individual fields

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-query-builder#38]
Although enableDistinctValues=true is a good choice for most fields, there are some fields where a list of values to choose from is not necessary or wanted.

This issue addresses a possible enhancement, e.g. for numeric fields that contain a lot of values:

Think of a field like POPULATION, where a query will usually be POPULATION >= 500000. For this kind of numeric field I would like to disable the distinct-value capability without disabling it for every other field as well.

**Comment by sholtkamp** [comment]
This issue can be solved by setting the property "enableInitialDistinctValues" to false
