### ISSUE TITLE
Queries with umlauts are not supported

### ISSUE THREAD

**Issue by StefanMenze** [conterra/mapapps-query-builder#4]
Its not possible the create a query with umlauts

**Comment by matthiasstein** [comment]
Could you give me more information about this bug?

**Comment by StefanMenze** [comment]
I try different queries with different AGS Services yet. Now I can delimit it.
Its not possible the create a query with umlauts when I use Services that are secure by the security.manager (sso with iwa).
When I use an AGS token based Map Service it works great

**Comment by matthiasstein** [comment]
Could you try to use the omnisearch to perform a query to the affected service?

**Comment by StefanMenze** [comment]
I try it. its not possible as well. Just without umlauts the omnisearch work correctly.

**Comment by matthiasstein** [comment]
I infer from this that it is no QueryBuilder problem. Please contact the conterra support.
