### ISSUE TITLE
Result store appears in selection tool

### ISSUE THREAD

**Issue by kknoppe** [conterra/mapapps-query-builder#43]
Problem:
After a search is executed I open the map.apps selection-ui. The list contains a duplicate of the layer that I searched on previously.

![image](https://user-images.githubusercontent.com/86719076/136929843-d6489dbf-4c3f-4a12-aa97-44227db0fde6.png)

Fix:
Remove "selection" in useIn: ["selection"] in the QueryController:
![image](https://user-images.githubusercontent.com/86719076/136930117-0cb84b06-4f64-4184-a388-b22933bf41de.png)

**Comment by matthiasstein** [comment]
This error cannot be reproduced.
