### ISSUE TITLE
Sample Queries not working properly in map.apps 4.12.0

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-query-builder#45]
The sample queries provided do not work properly as of now:
- Using the query "Show reported street damages that are not yet fixed in Münster" twice in succession returns the warning "Keine Ergebnisse für Ihre Abfrage gefunden"
- Using either of the queries targeting the layer "wahlkreise_strukturdaten" returns the error "compareFields: requires at least one field"

These issues also persist in the map.apps 4.13.0-SNAPSHOT version

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/commit/eb356e6b4c551399a67908647fd964da404b1683
