### ISSUE TITLE
Cannot filter results using wildcards

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-query-builder#6]
When filtering results using wildcards, for example *feature, "No data" is displayed, even though data exists.

How to reproduce: see file attached.

[result_center_filter_bug.pdf](https://github.com/conterra/mapapps-query-builder/files/456166/result_center_filter_bug.pdf)

**Comment by matthiasstein** [comment]
It is no bug. The ResultCenter doesn't support wildcards.
