### ISSUE TITLE
Combobox shows double entries -fixed with css!

### ISSUE THREAD

**Issue by cristina-laixo** [conterra/mapapps-query-builder#66]
We had a problem after updating the bundle to the last version: in the query builder comboboxes, there were double entries: not only field lables, e.g. "Status[object object]" or for the function e.g. "equals equals". We resolved this by adding an entry to the style in the bundle's styles.css. Please add this fix (or one that you consider to work) to the official bundle styles.css. In your example app, this style comes from the autumn theme, but in our case (even if we built our custom theme after autumn) it just wasn't there.

.ctAppRoot .querybuilder-window .vue-base .v-select__selections .v-input:not(.v-input--is-disabled) {
opacity: 0;
}

![image-20230623-083826](https://github.com/conterra/mapapps-query-builder/assets/134689345/ca589cee-301c-4cf6-993f-7c4a7dbc7312)

**Comment by sholtkamp** [comment]
Cannot reproduce.
This was most likely caused by an outdated theme.

Please reopen if the issues persists.
