### ISSUE TITLE
Cannot remove selected items from resultcenter

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-query-builder#7]
One cannot reomove selected items from the resultcenter since the button is grayed out.

How to reproduce: see file attached.
[result_center_removetool_bug.pdf](https://github.com/conterra/mapapps-query-builder/files/456176/result_center_removetool_bug.pdf)

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/v3.2.0
