### ISSUE TITLE
Cannot perform featureinfo after features were added to resultcenter

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-query-builder#9]
## Reproduction
- Add a service to map.apps
- Assure that featureinfo works in this app
- Perform a query
- Resultcenter opens
- Perform another featureinfo

## Expected
- featureinfo opens

## Actual
- featureinfo does not open, even after emptying resultcenter

## Note
- An app is attached
- tested with querybuilder 3.2.1 and map.apps 3.7.0. Customer uses 3.6.0.
[querybuilder_resultcenter.zip](https://github.com/conterra/mapapps-query-builder/files/810978/querybuilder_resultcenter.zip)

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-query-builder/releases/tag/v3.2.2
